runtime: python38

env_variables:
  CLOUD_SQL_USERNAME: surveyRating
  CLOUD_SQL_PASSWORD: 12345
  CLOUD_SQL_DATABASE_NAME: customer_survey_db
  CLOUD_SQL_CONNECTION_NAME: ageless-welder-312500:us-central1:customer-survey-rating-12345
  
  

